services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - /home/${USER}/data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   depends_on:
  #     - mariadb
  #   environment:
  #     - DB_HOST=mariadb
  #     - DB_NAME=${MYSQL_DATABASE}
  #     - DB_USER=${MYSQL_USER}
  #     - DB_PASSWORD=${MYSQL_USER_PWD}
  #     - DOMAIN_NAME=${DOMAIN_NAME}
  #     - WP_TITLE=${WP_TITLE}
  #     - WP_ADMIN_USER=${WP_ADMIN_USER}
  #     - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
  #     - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
  #     - WP_USER=${WP_USER}
  #     - WP_USER_EMAIL=${WP_USER_EMAIL}
  #     - WP_USER_PASSWORD=${WP_USER_PASSWORD}
  #   volumes:
  #     - /home/${USER}/data/wordpress:/var/www/html
  #   networks:
  #     - inception
  #   restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    # depends_on:
    #   - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge
    