services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  redis:
    build: ./requirements/redis
    container_name: redis
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=mariadb
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_USER_PWD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - www-data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - adminer
    ports:
      - "443:443"
    volumes:
      - www-data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  adminer:
    build: ./requirements/adminer
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge

volumes:
  www-data:
    driver_opts:
      type: local
      device: /home/${USER}/data/www-data
      o: bind
  db-data:
    driver_opts:
      type: none
      device: /home/${USER}/data/data-db
      o: bind