FROM alpine@sha256:b6a6be0ff92ab6db8acd94f5d1b7a6c2f0f5d10ce3c24af348d333ac6da80685

RUN apk add --no-cache busybox-extras

WORKDIR /var/www

COPY index.html .
COPY style.css .

EXPOSE 8079

CMD ["httpd", "-f", "-v", "-p", "8079"]